apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-auth
  name: postgres-auth
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-auth
