apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-auth-data
  name: postgres-auth-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
