// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenProvider is an autogenerated mock type for the RefreshTokenProvider type
type RefreshTokenProvider struct {
	mock.Mock
}

// GetRefreshToken provides a mock function with given fields: ctx, tokenID
func (_m *RefreshTokenProvider) GetRefreshToken(ctx context.Context, tokenID string) (*string, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*string, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = rf(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRefreshTokenProvider creates a new instance of RefreshTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenProvider {
	mock := &RefreshTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
